version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    CLUSTER_NAME: my-cluster
    APP_NAME: html-app
    IMAGE_NAME: html-app
    ECR_REPOSITORY: html-app

phases:
  pre_build:
    commands:
      - echo "Login to ECR"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_REGISTRY=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo "Build and Push Image"
      - docker build -t $IMAGE_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker tag $IMAGE_NAME:$CODEBUILD_BUILD_NUMBER $ECR_REGISTRY/$ECR_REPOSITORY:$CODEBUILD_BUILD_NUMBER
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo "Deploy to EKS"
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - export IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$CODEBUILD_BUILD_NUMBER

      - sed -i "s|{{IMAGE}}|$IMAGE|g" deployment.yaml
      - sed -i "s|{{APP_NAME}}|$APP_NAME|g" deployment.yaml

      - kubectl apply -f deployment.yaml
      - kubectl rollout status deployment/$APP_NAME
